/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as PressRouteImport } from './routes/press'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as NsphereRouteImport } from './routes/nsphere'
import { Route as LumexOnlineRouteImport } from './routes/lumex-online'
import { Route as LumexRouteImport } from './routes/lumex'
import { Route as HouseRouteImport } from './routes/house'
import { Route as FortunoffRouteImport } from './routes/fortunoff'
import { Route as DiamondsRouteImport } from './routes/diamonds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AtelierAmaraRouteImport } from './routes/atelier-amara'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const NsphereRoute = NsphereRouteImport.update({
  id: '/nsphere',
  path: '/nsphere',
  getParentRoute: () => rootRouteImport,
} as any)
const LumexOnlineRoute = LumexOnlineRouteImport.update({
  id: '/lumex-online',
  path: '/lumex-online',
  getParentRoute: () => rootRouteImport,
} as any)
const LumexRoute = LumexRouteImport.update({
  id: '/lumex',
  path: '/lumex',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const FortunoffRoute = FortunoffRouteImport.update({
  id: '/fortunoff',
  path: '/fortunoff',
  getParentRoute: () => rootRouteImport,
} as any)
const DiamondsRoute = DiamondsRouteImport.update({
  id: '/diamonds',
  path: '/diamonds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierAmaraRoute = AtelierAmaraRouteImport.update({
  id: '/atelier-amara',
  path: '/atelier-amara',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier-amara': typeof AtelierAmaraRoute
  '/contact': typeof ContactRoute
  '/diamonds': typeof DiamondsRoute
  '/fortunoff': typeof FortunoffRoute
  '/house': typeof HouseRoute
  '/lumex': typeof LumexRoute
  '/lumex-online': typeof LumexOnlineRoute
  '/nsphere': typeof NsphereRoute
  '/platform': typeof PlatformRoute
  '/press': typeof PressRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier-amara': typeof AtelierAmaraRoute
  '/contact': typeof ContactRoute
  '/diamonds': typeof DiamondsRoute
  '/fortunoff': typeof FortunoffRoute
  '/house': typeof HouseRoute
  '/lumex': typeof LumexRoute
  '/lumex-online': typeof LumexOnlineRoute
  '/nsphere': typeof NsphereRoute
  '/platform': typeof PlatformRoute
  '/press': typeof PressRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier-amara': typeof AtelierAmaraRoute
  '/contact': typeof ContactRoute
  '/diamonds': typeof DiamondsRoute
  '/fortunoff': typeof FortunoffRoute
  '/house': typeof HouseRoute
  '/lumex': typeof LumexRoute
  '/lumex-online': typeof LumexOnlineRoute
  '/nsphere': typeof NsphereRoute
  '/platform': typeof PlatformRoute
  '/press': typeof PressRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atelier-amara'
    | '/contact'
    | '/diamonds'
    | '/fortunoff'
    | '/house'
    | '/lumex'
    | '/lumex-online'
    | '/nsphere'
    | '/platform'
    | '/press'
    | '/technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atelier-amara'
    | '/contact'
    | '/diamonds'
    | '/fortunoff'
    | '/house'
    | '/lumex'
    | '/lumex-online'
    | '/nsphere'
    | '/platform'
    | '/press'
    | '/technology'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atelier-amara'
    | '/contact'
    | '/diamonds'
    | '/fortunoff'
    | '/house'
    | '/lumex'
    | '/lumex-online'
    | '/nsphere'
    | '/platform'
    | '/press'
    | '/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtelierAmaraRoute: typeof AtelierAmaraRoute
  ContactRoute: typeof ContactRoute
  DiamondsRoute: typeof DiamondsRoute
  FortunoffRoute: typeof FortunoffRoute
  HouseRoute: typeof HouseRoute
  LumexRoute: typeof LumexRoute
  LumexOnlineRoute: typeof LumexOnlineRoute
  NsphereRoute: typeof NsphereRoute
  PlatformRoute: typeof PlatformRoute
  PressRoute: typeof PressRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nsphere': {
      id: '/nsphere'
      path: '/nsphere'
      fullPath: '/nsphere'
      preLoaderRoute: typeof NsphereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumex-online': {
      id: '/lumex-online'
      path: '/lumex-online'
      fullPath: '/lumex-online'
      preLoaderRoute: typeof LumexOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumex': {
      id: '/lumex'
      path: '/lumex'
      fullPath: '/lumex'
      preLoaderRoute: typeof LumexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fortunoff': {
      id: '/fortunoff'
      path: '/fortunoff'
      fullPath: '/fortunoff'
      preLoaderRoute: typeof FortunoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diamonds': {
      id: '/diamonds'
      path: '/diamonds'
      fullPath: '/diamonds'
      preLoaderRoute: typeof DiamondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier-amara': {
      id: '/atelier-amara'
      path: '/atelier-amara'
      fullPath: '/atelier-amara'
      preLoaderRoute: typeof AtelierAmaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtelierAmaraRoute: AtelierAmaraRoute,
  ContactRoute: ContactRoute,
  DiamondsRoute: DiamondsRoute,
  FortunoffRoute: FortunoffRoute,
  HouseRoute: HouseRoute,
  LumexRoute: LumexRoute,
  LumexOnlineRoute: LumexOnlineRoute,
  NsphereRoute: NsphereRoute,
  PlatformRoute: PlatformRoute,
  PressRoute: PressRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
